services:
  johnny-payment-1: &johnny-payment
    hostname: johnny-payment-1
    build:
      context: ./
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    networks:
      - backend
      - payment-processor
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      johnny-redis:
        condition: service_healthy

  johnny-payment-2:
    <<: *johnny-payment
    hostname: johnny-payment-2
    ports:
      - "8081:8080"

  johnny-redis:
    hostname: johnny-redis
    image: redis:8.0.3-alpine
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  johnny-nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - johnny-payment-1
      - johnny-payment-2

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
