services:
  johnny-payment:
    hostname: johnny-payment
    build:
      context: ./
      dockerfile: Dockerfile.local
    ports:
      - "9999:8080"
    networks:
      - backend
      - payment-processor
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      johnny-redis:
        condition: service_healthy

  johnny-redis:
    hostname: johnny-redis
    image: redis:8.0.3-alpine
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
