services:
  johnny-payment-1: &johnny-payment
    hostname: johnny-payment-1
    build: .
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "140MB"

  johnny-payment-2:
    <<: *johnny-payment
    hostname: johnny-payment-2

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - johnny-payment-1
      - johnny-payment-2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "70MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
