FROM eclipse-temurin:24-jdk-alpine
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
WORKDIR /app
COPY . /app
RUN ./mvnw dependency:go-offline
CMD ["./mvnw", "spring-boot:run"]
